CL SCR;
CREATE OR REPLACE PROCEDURE get_role_priv_ins_or_del_on_table
(
   CURSOR_ OUT SYS_REFCURSOR, 
   pi_Role_Name IN NVARCHAR2,
   pi_table_name IN NVARCHAR2,
   pi_priv IN NVARCHAR2
)
AS
BEGIN
   OPEN CURSOR_ FOR
      SELECT ROLE, PRIVILEGE,  GRANTABLE GRANT_WITH
      FROM ROLE_TAB_PRIVS
      WHERE ROLE = pi_role_Name AND TABLE_NAME = pi_table_name AND PRIVILEGE = pi_priv;
END;

CL SCR;
SET SERVEROUTPUT ON;
variable cur refcursor;
variable role_Name NVARCHAR2;
execute get_role_priv_ins_or_del_on_table(:cur,'BAC_SI', 'HOSOBENHAN', 'SELECT');
print cur;

CREATE ROLE BAC_SI;
GRANT SELECT(KETLUANCUARBS), UPDATE, DELETE ON HOSOBENHAN TO BAC_SI;
GRANT SELECT(KETLUANCUABS)ON HOSOBENHAN TO BAC_SI
REVOKE SELECT ON HOSOBENHAN FROM BAC_SI
GRANT UPDATE(HOTEN, NGAYSINH) ON BENHNHAN TO BAC_SI


SELECT ROLE, PRIVILEGE, COLUMN_NAME,  GRANTABLE GRANT_WITH
FROM ROLE_TAB_PRIVS
WHERE ROLE = 'BAC_SI' AND TABLE_NAME = 'HOSOBENHAN'


