CL SCR;
CREATE OR REPLACE PROCEDURE get_role_privs_delete_on_table
(
   CURSOR_ OUT SYS_REFCURSOR, 
   pi_Role_Name IN NVARCHAR2,
   pi_table_name IN NVARCHAR2
)
AS
BEGIN
   OPEN CURSOR_ FOR
      SELECT ROLE, PRIVILEGE, COLUMN_NAME, GRANTABLE GRANT_WITH
      FROM ROLE_TAB_PRIVS
      WHERE ROLE = pi_role_Name AND TABLE_NAME = pi_table_name AND PRIVILEGE = 'DELETE';
END;

CL SCR;
variable cur refcursor;
variable role_Name NVARCHAR2;
execute get_role_privs_delete_on_table(:cur,'BAC_SI', 'HOSOBENHAN');
print cur;

CREATE ROLE BAC_SI;
GRANT SELECT, UPDATE, DELETE ON HOSOBENHAN TO BAC_SI;
GRANT SELECT(KETLUANCUABS)ON HOSOBENHAN TO BAC_SI
REVOKE SELECT ON HOSOBENHAN FROM BAC_SI
GRANT UPDATE(HOTEN, NGAYSINH) ON BENHNHAN TO BAC_SI
